-- Seeded from the work.html grid, the current source of truth for slug,
-- title, client, sector, disciplines, cover and running order.
insert into web.projects (slug,title,client,sector,tags,cover,position) values
 ('disney-plus','Disney+',null,'Culture & Immersive',array['3D','Art','Animation','Immersive']::text[],'assets/img/projects/disney-plus/illusorr-disney-plus-streaming-brand-campaign-cover.webp',1),
 ('hind-al-oud','Hind Al Oud',null,'Beauty & Fragrance',array['AI Content','Campaign','Film','Social Media']::text[],'assets/img/projects/hind-al-oud/illusorr-hind-al-oud-outdoor-billboard-visual.webp',2),
 ('u-hub-metaverse','U-Hub Metaverse','Unilever','Gaming, Worlds & IP',array['Metaverse','3D','Real Time','Immersive']::text[],'assets/img/projects/u-hub-metaverse/illusorr-u-hub-metaverse-virtual-campus-hub-cover.webp',3),
 ('pixelpaint','PixelPaint','ABB Robotics','Business & Institutions',array['Art','Installation']::text[],'assets/img/projects/pixelpaint/illusorr-pixelpaint-generative-bloom-hero.webp',4),
 ('art-post-office','Art Post Office',null,'Fashion, Retail & Jewellery',array['AI Content','Product Design','Social Media']::text[],'assets/img/projects/art-post-office/illusorr-art-post-office-monthly-delivery-frame-01.webp',5),
 ('metagenus','Metagenus',null,'Gaming, Worlds & IP',array['Original IP','3D','Art']::text[],'assets/img/projects/metagenus/cover.webp',6),
 ('pera','Pera','Koton','Fashion, Retail & Jewellery',array['AI Content','Campaign','Social Media']::text[],'assets/img/projects/pera/illusorr-pera-concrete-editorial-campaign-cover.webp',7),
 ('optiverse','Optiverse','Optima','Gaming, Worlds & IP',array['Metaverse','3D','Art','Immersive','Real Time']::text[],'assets/img/projects/optiverse/illusorr-optiverse-connected-virtual-worlds-hub-cover.webp',8),
 ('khaltat','Khaltat',null,'Beauty & Fragrance',array['AI Content','Campaign','Social Media','Ecommerce']::text[],'assets/img/projects/khaltat/illusorr-khaltat-fragrance-ecommerce-content-cover.webp',9),
 ('illusorr-spaces','ILLUSORR Spaces',null,'Gaming, Worlds & IP',array['Original IP','Metaverse','3D','Real Time','Immersive']::text[],'assets/img/projects/illusorr-spaces/illusorr-spaces-multiuser-immersive-environment-cover.webp',10),
 ('barbie','Barbie','Boyner','Fashion, Retail & Jewellery',array['AI Content','Campaign','Social Media','3D']::text[],'assets/img/projects/barbie/illusorr-barbie-digital-fashion-doll-cover.webp',11),
 ('trt-metaverse','TRT Metaverse',null,'Gaming, Worlds & IP',array['Metaverse','3D','Real Time','Immersive']::text[],'assets/img/projects/trt-metaverse/illusorr-trt-metaverse-broadcast-virtual-studio-cover.webp',12),
 ('coffee-merchant','Coffee Merchant',null,'Business & Institutions',array['AI Content','Social Media']::text[],'assets/img/projects/coffee-merchant/illusorr-coffee-merchant-specialty-coffee-content-cover.webp',13),
 ('lapillus','Lapillus',null,'Real Estate & Architecture',array['Archi viz','3D','AI Content','Web','Film','Social Media']::text[],'assets/img/projects/lapillus/illusorr-lapillus-pebble-concept-form.webp',14),
 ('aquatic-architects','Aquatic Architects',null,'Real Estate & Architecture',array['Archi viz','3D','Web','AI Content','Social Media']::text[],'assets/img/projects/aquatic-architects/illusorr-aquatic-architects-floating-villa-render-cover.webp',15),
 ('fabrika','Fabrika','Boyner','Fashion, Retail & Jewellery',array['AI Content','Campaign','Social Media']::text[],'assets/img/projects/fabrika/illusorr-fabrika-boyner-campaign-cover.webp',16),
 ('ant-systems','ANT Systems',null,'Business & Institutions',array['Web','3D','Animation']::text[],'assets/img/projects/ant-systems/illusorr-ant-systems-factory-signage-cover.webp',17),
 ('anfasic','Anfasic',null,'Beauty & Fragrance',array['AI Content','Social Media','3D']::text[],'assets/img/projects/anfasic/illusorr-anfasic-dokhoon-product-render-14.webp',18),
 ('michael-cinco','Michael Cinco',null,'Beauty & Fragrance',array['AI Content','Campaign','Ecommerce']::text[],'assets/img/projects/michael-cinco/illusorr-michael-cinco-campaign-frame-01.webp',19),
 ('koton-lookbook-russia','Koton Lookbook Russia',null,'Fashion, Retail & Jewellery',array['AI Content','Campaign','Social Media']::text[],'assets/img/projects/koton-lookbook-russia/illusorr-koton-lookbook-russia-campaign-cover.webp',20),
 ('denim','Denim','Boyner','Fashion, Retail & Jewellery',array['AI Content','Campaign','Social Media']::text[],'assets/img/projects/denim/illusorr-denim-boyner-diner-daylight-campaign.webp',21),
 ('morphellum','Morphellum','DressX','Fashion, Retail & Jewellery',array['3D','Art','Original IP']::text[],'assets/img/projects/morphellum/illusorr-morphellum-machimatch-digital-garment-artwork.webp',22),
 ('riyadhverse','Riyadhverse','Bawtaqah','Real Estate & Architecture',array['3D','Archi viz','Real Time','Immersive']::text[],'assets/img/projects/riyadhverse/illusorr-riyadhverse-riyadh-digital-twin-aerial-cover.webp',23),
 ('pylon','Pylon',null,'Gaming, Worlds & IP',array['Original IP','3D','Art','Real Time','Metaverse','Immersive']::text[],'assets/img/projects/pylon/illusorr-pylon-owned-launch-world-cover.webp',24),
 ('echoes-of-light','Echoes of Light','Hybrid Xperience','Culture & Immersive',array['Installation','Immersive','Art','3D']::text[],'assets/img/projects/echoes-of-light/illusorr-echoes-of-light-immersive-light-installation-cover.webp',25),
 ('metaculture','Metaculture',null,'Culture & Immersive',array['Metaverse','3D','Art','Immersive','Real Time']::text[],'assets/img/projects/metaculture/illusorr-metaculture-digital-fashion-exhibition-cover.webp',26),
 ('al-berwaz','Al Berwaz',null,'Business & Institutions',array['Web','Branding']::text[],'assets/img/projects/al-berwaz/illusorr-al-berwaz-insurance-web-platform-cover.webp',27),
 ('arga','Arga',null,'Business & Institutions',array['Web','Branding']::text[],'assets/img/projects/arga/illusorr-arga-global-team-interface-cover.webp',28),
 ('moodie-kiosk','Moodie Kiosk',null,'Business & Institutions',array['Product Design','3D']::text[],'assets/img/projects/moodie-kiosk/illusorr-moodie-kiosk-retail-unit-render-01.webp',29)
on conflict (slug) do update set title=excluded.title, client=excluded.client, sector=excluded.sector, tags=excluded.tags, cover=excluded.cover, position=excluded.position;
